### ISSUE TITLE
memoryerror

### ISSUE THREAD

**Issue by Jolntu** [ale152/muvilab#5]
when "current_mosaic = np.zeros((n_frames, fdim[0]*self.Ny, fdim[1]*self.Nx, 3))" always memoryerror

**Comment by ale152** [comment]
Hi @Jolntu , thank you for reporting it. I will fix this later today and push an update.

**Comment by BigBugGrow** [comment]
File "C:\Users\Administrator\Downloads\muvilab-0.2.9\annotator.py", line 268, in create_mosaic
    current_mosaic = np.zeros((n_frames, fdim[0]*self.Ny, fdim[1]*self.Nx, 3), dtype=np.uint8)

**Comment by BigBugGrow** [comment]
still have MemoryError
 File "C:\Users\Administrator\Downloads\muvilab-0.2.9\annotator.py", line 268, in create_mosaic
    current_mosaic = np.zeros((n_frames, fdim[0]*self.Ny, fdim[1]*self.Nx, 3), dtype=np.uint8)

**Comment by ale152** [comment]
@BigBugGrow how many frames are the video clips that you're trying to annotate? And how big are they?

**Comment by BigBugGrow** [comment]
a 40mins video
100 frames in a video clip
